import datetime
import psycopg2
import pandas as pd

from pprint import pprint
from configparser import ConfigParser

################################################################
### Options to display complete set of data frame in console ###
################################################################

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# records = [('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 1),
#   1380.0,
#   1385.2),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 5),
#   1391.0,
#   1409.9),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 6),
#   1423.0,
#   1411.05),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 7),
#   1410.25,
#   1430.2),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 8),
#   1430.0,
#   1439.85),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 9),
#   1455.0,
#   1441.05),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 12),
#   1474.0,
#   1425.75),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 13),
#   1433.0,
#   1397.15),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 15),
#   1332.3,
#   1360.75),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 16),
#   1365.0,
#   1353.75),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 19),
#   1340.0,
#   1362.55),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 20),
#   1379.0,
#   1351.35),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 22),
#   1355.55,
#   1351.1),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 23),
#   1343.0,
#   1333.8),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 26),
#   1332.25,
#   1343.55),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 27),
#   1346.0,
#   1348.5),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 28),
#   1358.0,
#   1356.0),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 29),
#   1368.0,
#   1356.35),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 30),
#   1346.3,
#   1354.35),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 3),
#   1340.8,
#   1352.05),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 4),
#   1354.0,
#   1329.4),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 5),
#   1341.1,
#   1341.5),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 6),
#   1345.0,
#   1361.6),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 7),
#   1365.3,
#   1352.55),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 10),
#   1349.85,
#   1339.55),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 11),
#   1336.9,
#   1330.65),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 12),
#   1330.0,
#   1327.0),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 14),
#   1326.85,
#   1316.4),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 17),
#   1320.3,
#   1329.4),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 18),
#   1338.0,
#   1340.0),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 19),
#   1342.0,
#   1337.0),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 20),
#   1348.4,
#   1339.3),
#  ('Infosys Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 21),
#   1347.5,
#   1354.5),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 1),
#   3191.1,
#   3165.0),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 5),
#   3171.0,
#   3238.9),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 6),
#   3275.0,
#   3264.7),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 7),
#   3259.0,
#   3271.4),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 8),
#   3270.0,
#   3317.35),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 9),
#   3354.0,
#   3322.25),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 12),
#   3322.25,
#   3246.55),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 13),
#   3214.0,
#   3104.05),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 15),
#   3160.3,
#   3218.95),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 16),
#   3229.0,
#   3195.15),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 19),
#   3169.0,
#   3161.8),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 20),
#   3225.0,
#   3144.55),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 22),
#   3148.0,
#   3118.8),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 23),
#   3105.0,
#   3109.5),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 26),
#   3102.05,
#   3100.8),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 27),
#   3106.0,
#   3132.0),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 28),
#   3149.95,
#   3124.1),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 29),
#   3145.6,
#   3115.25),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 30),
#   3099.0,
#   3035.65),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 3),
#   3024.9,
#   3037.0),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 4),
#   3062.8,
#   3049.75),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 5),
#   3070.0,
#   3095.7),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 6),
#   3105.5,
#   3111.45),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 7),
#   3133.0,
#   3132.9),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 10),
#   3145.95,
#   3145.5),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 11),
#   3125.0,
#   3122.6),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 12),
#   3120.0,
#   3087.6),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 14),
#   3098.5,
#   3051.5),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 17),
#   3055.0,
#   3069.75),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 18),
#   3100.0,
#   3088.8),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 19),
#   3084.0,
#   3082.0),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 20),
#   3067.1,
#   3060.0),
#  ('Tata Consultancy Services Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 21),
#   3061.0,
#   3080.5),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 1),
#   418.85,
#   416.4),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 5),
#   416.45,
#   425.45),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 6),
#   427.95,
#   427.15),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 7),
#   425.0,
#   438.0),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 8),
#   441.95,
#   442.1),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 9),
#   442.9,
#   450.1),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 12),
#   450.0,
#   432.6),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 13),
#   432.0,
#   418.95),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 15),
#   418.9,
#   430.7),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 16),
#   441.7,
#   469.2),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 19),
#   463.0,
#   472.75),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 20),
#   476.0,
#   470.1),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 22),
#   471.6,
#   486.65),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 23),
#   483.55,
#   475.7),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 26),
#   479.4,
#   480.3),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 27),
#   481.4,
#   485.05),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 28),
#   485.85,
#   489.3),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 29),
#   492.7,
#   489.85),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 4, 30),
#   491.5,
#   492.75),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 3),
#   487.95,
#   487.35),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 4),
#   487.3,
#   481.95),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 5),
#   484.8,
#   490.6),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 6),
#   493.7,
#   512.3),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 7),
#   514.0,
#   515.25),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 10),
#   517.6,
#   525.95),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 11),
#   517.95,
#   518.4),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 12),
#   519.95,
#   507.6),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 14),
#   507.5,
#   498.45),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 17),
#   498.45,
#   499.8),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 18),
#   502.0,
#   508.05),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 19),
#   508.3,
#   511.65),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 20),
#   516.0,
#   508.25),
#  ('Wipro Limited',
#   'Information Technology',
#   'IT Services & Consulting',
#   datetime.date(2021, 5, 21),
#   510.0,
#   512.7)]

###################################
### Get inputs from config file ###
###################################
config = ConfigParser()
config.read('../FlaskScreener/config.ini')

#################
### DB config ###
#################
databaseName = config.get('Database', 'databaseName')
user = config.get('Database', 'user')
password = config.get('Database', 'password')
host = config.get('Database', 'host')
port = config.get('Database', 'port')

db = psycopg2.connect(database=databaseName, user=user, password=password, host=host, port=port)
conn = db.cursor()

conn.execute("""SELECT 
                  instruments.nameofcompany, 
                  instruments.sector, 
                  instruments.subsector, 
                  eod.date,
                  eod.open,
                  eod.close
                FROM 
                  eod 
                  INNER JOIN instruments ON instruments.id = eod.instruments_id""")
                # WHERE
                #   instruments.symbol IN ('INFY', 'TCS', 'WIPRO')""")
records = conn.fetchall()

conn.execute("""SELECT DISTINCT(date) FROM eod ORDER BY date ASC""")
columns = conn.fetchall()

# pprint(records)
# pprint(columns)

candles_1 = {}

for column in columns:
    for record in records:
        if column[0] == record[3]:
            # print(f"Company: {record[0]}, Sector: {record[1]}, Sub-Sector: {record[2]}, Date: {record[3]}, Open: {record[4]}, Close: {record[5]}")
            try:
                if column[0] in candles_1[record[0]]:
                    # candles_1[record[0]][column[0]]["open"] = record[4]
                    # candles_1[record[0]][column[0]]["close"] = record[5]
                    # candles_1[record[0]][column[0]]["percentChange"] = round((((record[5] - record[4]) * 100) / record[4]), 2)
                    candles_1[record[0]][column[0]] = round((((record[5] - record[4]) * 100) / record[4]), 2)
                else:
                    candles_1[record[0]][column[0]] = {}
                    # candles_1[record[0]][column[0]]["open"] = record[4]
                    # candles_1[record[0]][column[0]]["close"] = record[5]
                    # candles_1[record[0]][column[0]]["percentChange"] = round((((record[5] - record[4]) * 100) / record[4]), 2)
                    candles_1[record[0]][column[0]] = round((((record[5] - record[4]) * 100) / record[4]), 2)
            except KeyError:
                if record[0] not in candles_1:
                    candles_1[record[0]] = {}
                if column[0] not in candles_1[record[0]]:
                    candles_1[record[0]][column[0]] = {}
                    # candles_1[record[0]][column[0]]["open"] = record[4]
                    # candles_1[record[0]][column[0]]["close"] = record[5]
                    # candles_1[record[0]][column[0]]["percentChange"] = round((((record[5] - record[4]) * 100) / record[4]), 2)
                    candles_1[record[0]][column[0]] = round((((record[5] - record[4]) * 100) / record[4]), 2)

# List to pandas conversion
df = pd.DataFrame(candles_1).T

pprint(df)

# iterating the columns
for col in df.columns:
    print(col)

# iterating the index
for row in df.index:
    print(row)

# iterating the rows
for col in df.columns:
    for row in df.index:
        print(df[col][row])




